services:
  audit_service:
    container_name: audit_service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    environment:
      TZ: 'America/Sao_Paulo'
    depends_on:
      - kafka
      - audit_mongodb
    networks:
      - biz_audit_network

  audit_mongodb:
    container_name: audit_mongodb
    restart: always
    image: mongo:latest
    ports:
      - "2222:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/backup
      - mongo_logs:/var/log/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: audit_mongodb
    networks:
      - biz_audit_network
    command: [ "mongod", "--journal" ]

  zookeeper:
    container_name: zookeeper
    restart: always
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - biz_audit_network

  kafka:
    container_name: kafka
    restart: always
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    networks:
      - biz_audit_network

  control-center:
    container_name: control-center
    restart: always
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      PORT: 9021
    networks:
      - biz_audit_network

networks:
  biz_audit_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  mongo_backup:
    driver: local
  mongo_logs:
    driver: local
